### ISSUE TITLE
Make the window wider

### ISSUE THREAD

**Issue by ShadyMedic** [nullTheCoder/500mb_jar_installer#2]
The names of the files being downloaded are usually cut off, the path can never fit into the window whole and it doesn't look like it'd hurt anything if it was wider.
![image](https://user-images.githubusercontent.com/19894267/186729750-5f6c7903-8ff0-4276-91b9-890abb7773eb.png)

**Comment by nullTheCoder** [comment]
Made the window wider a bit.

**Comment by ShadyMedic** [comment]
Looks better, some of the file names still can't fit on the screen though. I'm not going to reopend this because of something this minor, but could you perhaps please make the text break when it can't fit on one line?
