### ISSUE TITLE
Disable controlls when an operation is in process

### ISSUE THREAD

**Issue by ShadyMedic** [nullTheCoder/500mb_jar_installer#3]
The `Install` and `Open` buttons are clickable, the file path text box is also alterable and the same goes for the version select box.

Maybe it'd be nice to grey these controls out when there's an operation going on. I know that changing or clicking anything of that won't probably break anything, but it looks a bit weird.

**Comment by nullTheCoder** [comment]
It isn't greyed out but you can not interact with it while it is downloading.
