### ISSUE TITLE
Auto-select an existing mod file

### ISSUE THREAD

**Issue by ShadyMedic** [nullTheCoder/500mb_jar_installer#4]
When changing the versions in the select box, the file name in the file path text box changes accordingly. However, this usually results in the new version being downloaded as a whole and avoids update of any existing version.

Would it be possible to fill the text box with a path to the first file containing `VoicesOfWynn` in its name, which is located in the default install location? And not change it unless the user explicitly specifies a different file name.

**Comment by ShadyMedic** [comment]
Hmm, doesn't seem to be fixed. It can usually detect a file that has the same name as one of the versions, but if I rename `VoicesOfWynn-Demo.jar` to `VoicesOfWynn-Demosssss.jar`, it won't detect it and install the selected version from zero.

**Comment by nullTheCoder** [comment]
I fixed it at least partially.

**Comment by ShadyMedic** [comment]
Can confirm.
