### ISSUE TITLE
Confirmation dialogue boxes have one extra button

### ISSUE THREAD

**Issue by ShadyMedic** [nullTheCoder/500mb_jar_installer#5]
The rename/overwrite confirmation dialogues have three buttons:

1. Yes
2. No
3. Cancel

Only the first two (or first and third) make sense.

I know that this might not be trivial, given how the dialogue boxes are preset, but if possible, could you remove the third button?
![image](https://user-images.githubusercontent.com/19894267/186731489-c5479953-b80f-4e27-af8f-77a7eaa5e56a.png)
Also, maybe it'd be nice if the string in the dialogue box navbar was more specific, these looks a bit like default values.

**Comment by nullTheCoder** [comment]
Made it be only yes and no.
