### ISSUE TITLE
The file select dialogue always points to my Documents folder

### ISSUE THREAD

**Issue by ShadyMedic** [nullTheCoder/500mb_jar_installer#6]
No matter what's in the text box, when I click the `Open` button, I'm always in my "Documents" folder.

It'd be nice if it could open the dialogue inside the folder containing the file specified in the text box.

**Comment by nullTheCoder** [comment]
Fixed by making it not do that, (it was a bug).

**Comment by ShadyMedic** [comment]
Works only during one session. If the app is restarted, it points to the documents folder again.

Also if I select a folder that doesn't contain any `.jar` file, it appends the name of the currently selected version (as it should), but also a slash which leads to inconsistency:
```
C:\Users\Shady\AppData\Roaming\.minecraft\config/VoicesOfWynn-Demo.jar
```

**Comment by nullTheCoder** [comment]
If it is still not working then it isn't really a problem with my code but more of a general java swing/windows problem.

**Comment by ShadyMedic** [comment]
Nope, seems to be fixed. Good job! 👍
