### ISSUE TITLE
The window is minimalized after clicking any button in dialogue boxes

### ISSUE THREAD

**Issue by ShadyMedic** [nullTheCoder/500mb_jar_installer#7]
Whenever I click a button in a dialogue box, the main window is minimalized.

**Comment by nullTheCoder** [comment]
I am not fixing this because this is a problem specifically in windows and I am pretty sure it can be disabled in windows settings so this has nothing to do with us, just windows being the worst OS to develop for.

**Comment by ShadyMedic** [comment]
How is it possible that this didn't happen in the previous snapshot? At least I don't remember it happening.

**Comment by ShadyMedic** [comment]
Actually, it seems to fix itself in the current version, as the window no longer minimalizes. Let's hope it stays this way.
