### ISSUE TITLE
Add a "Cancel" button

### ISSUE THREAD

**Issue by ShadyMedic** [nullTheCoder/500mb_jar_installer#8]
When an installation is in process, the user cannot stop it. Even the close button in the window's header is not responding. It looks like the application is frozen, except for the progress bar.

Would it be hard to replace the "Install" button with a "Cancel" button when an operation is running and make it operational? Alternatively, there can be the second button displayed next to "Install", with one of these being greyed out at any time.

**Comment by nullTheCoder** [comment]
Made Install button become cancel button when downloading.

**Comment by ShadyMedic** [comment]
Works nicely.

Just one bug: When the install finishes, the label of the button reverts back to "Install", but the callback function doesn't appear to be updated, since when I click it afterwards, the "Canceled" information text appears above the progress bar.

**Comment by nullTheCoder** [comment]
same as #1
